<?php
/** @var $block Yireo\ExampleJsComponent3\Block\Example */

// @todo: This is currently not working
?>
<div style="border: 1px solid #00A5E3; background-color: #efefef; padding: 10px;">
    <div data-mage-init='{"example3":{"message":"<?php echo $block->getMessage(); ?>"}}' data-bind="scope: 'example3'">
        <div data-bind="text: message">
            This should be replaced with some example
        </div>
    </div>
</div>
